# Generated by Django 2.2.5 on 2019-09-16 03:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='summary',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), default=list, size=None),
        ),
    ]
