# Generated by Django 2.2.5 on 2019-09-16 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_auto_20190915_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='summary',
            name='times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DurationField(), size=None),
        ),
    ]
