# Generated by Django 2.2.5 on 2019-10-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_auto_20190916_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='times',
        ),
        migrations.AddField(
            model_name='summary',
            name='Activities',
            field=models.ManyToManyField(to='Calendar.Activity'),
        ),
    ]
