# Generated by Django 2.2.5 on 2019-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_auto_20191024_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=100)),
                ('durationTime', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.AddField(
            model_name='summary',
            name='events',
            field=models.ManyToManyField(to='Calendar.Event'),
        ),
    ]
