# Generated by Django 2.2.5 on 2019-11-27 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_auto_20191024_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
